title: Jiajia Wu
logo: "/images/logo.jpg?raw=true"
description: >
  Northwestern University
  PHD Candiate
  Biomedical Engineering
  <br><br>
  MSU
  Bachelor in Electrical Engineering, Biomedical Concentration
  Honors College Member
  Minor in Cognitive Science
  <a href="https://www.linkedin.com/in/jiajia-wu-3a0715174/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
