title: Jiajia Wu 
theme: jekyll-theme-minimal
show_downloads: true
google_analytics: UA-134998524-1
github_url: https://github.com/bs3113
linkedin_url: https://www.linkedin.com/in/jiajia-wu-3a0715174/
